#!/usr/bin/env bash

#. .bryan.path.append $(dirname ${BASH_SOURCE[0]})/bin

#source $(dirname ${BASH_SOURCE[0]})/functions
#source $(dirname ${BASH_SOURCE[0]})/aliases

#!/usr/bin/env

. $(dirname ${BASH_SOURCE[0]})/init/init.sh
