#!/usr/bin/env bash

export BCH_QUICK__root=$(dirname $(dirname ${BASH_SOURCE[0]}))
export BCH_QUICK__bin=${BCH_QUICK__root}/.bch.bin
export BCH_QUICK__files=${BCH_QUICK__root}/.bch.files

. $(dirname ${BASH_SOURCE[0]})/init/init.sh

. q.init.sh
