#!/usr/bin/env python3
import sys
from pathlib import Path

if len(sys.argv)==1 : 
    print( f""" usage: 

    {Path(sys.argv[0]).name } LINE0 LINE1 ... | lpr -o orientation-requested=5
    """)
    exit()


for ii in range(39):
    print()
print( '------')
print( '------')
for line in sys.argv[1:]:
    print(line)
