#!/usr/bin/env bash

#---------------------------------------------------------------------------
# go to the directory of an executable file on path
#---------------------------------------------------------------------------

.go () {
    local xx
    for xx in . .-h .--help; do
        [ $xx == .${1} ] && {
            echo usage: .go NAME
            echo
            echo of NAME is found in PATH, pushd to its directory
            return
        }
    done
    which $1 || { echo not found: $1; return; }
    pushd $(dirname $(which $1))
}

#---------------------------------------------------------------------------
# pushd to a short link to current directory
#---------------------------------------------------------------------------

pusht () {
    case $1. in
        .|-h|--help)
            echo "usage: pusht <name>"
            echo "    pushd to /tmp/<name> --> \${PWD}"
            echo "    Handy to avoid overly long paths"
            ;;
        *)
            [ "${PWD::4}" == "/tmp" ] && echo alread in a temp link && return
            [ "${PWD::4}" == "/tmp" ] && return
            link=/tmp/$1
            rm $link
            ln -s ${PWD} ${link} || return
            pushd ${link}
    esac
}


git.status.root () {
    for name in $(ls -a ${1}); do
        path=${1}/${name}
        [ -d ${path}/.git ] || continue
        pushd ${path} > /dev/null
        __git_ps1
        printf "\t${path}\n"
        popd > /dev/null
    done
}

git.status () {
    git.status.root ~
    git.status.root ${__BCH_ROOT__}
    git.status.root ~/prj
}
