#!/usr/bin/env bash

cd $(dirname $0) > /dev/null

for name in $(ls $PWD/prj | grep ^bch); do
    real=$PWD/prj/$name/$name 
    [ -f $real ] || continue
    link=~/.local/bin/$(basename $real)
    rm $link 2> /dev/null
    ln -s $real $link
    echo installed $link 
done

