from .f_bold        import bold
from .f_fmap        import fmap
from .f_goodfolder  import goodfolder
from .f_isfile      import isfile
from .f_lines4path  import lines4path
from .f_listify     import listify
from .f_mkdirs      import mkdirs
from .f_strip4lines import strip4lines
from .f_text4lines  import text4lines
from .f_walk        import walk
