#!/usr/bin/env bash

:quick () {
    local qbin=~/.local/bin/bch.quick.d
    ::append:: $qbin
    local flag=${qbin}/flag.qbin
    [ $1. == -f. ] && rm -f ${flag}
    [ -f ${flag} ] && return
    rm -rf $qbin
    mkdir -p $qbin
    touch $flag

    for pth in $(find ${BCH_QUICK__root}/.bch/__bin__); do
        [ -d $pth ] && continue
        [ -f $pth ] && ln -s $pth $qbin/$(basename $pth)
        echo $pth
    done
}
:qbin () {
    :quick -f
}

:quick

bch:000:note "try [:qbin] to refresh qbin"

