#!/usr/bin/env bash

:go () {
    : go NAME
    :
    : pushd to directory containing file NAME
    local target
    target=$(dirname $(my.which $1) 2>/dev/null) && {
        echo pushd to $target
        pushd $target > /dev/null
        return
    }
    echo not found: $1
    return 99
}

