#!/bin/bash

:fhelp () {
    :
    : syntax:
    : :::: fn {name}
    : description:
    : :::: provide help on function {name} or script {name}
    :
    case  .$1 in .|.-h|.--help)
        ${FUNCNAME} ${FUNCNAME}
        #bch:fn:help bch:fn:help
        return
    esac

    declare -f $1 > /dev/null && {
        echo ------------------------------------------------
        declare -f $1 | fhelp.py
        return
    }
    echo "[${FUNCNAME}]  in body"
}


