#!/usr/bin/env bash

q:alias seagate  "/Volumes/SeagateBlue/mirrors/rsync.mirror.pumpkin.py"
q:alias prj      "pushd ~/prj"
q:alias l        "ls -G"
q:alias ll       "ls -1G"
q:alias bb       "bryan_buckets"
q:alias quick    "ls /Users/bch/.local/bin/bch.quick.d"
q:alias marco    "echo polo"
q:alias debug    "bch:000:debugger"
q:alias q:help   ". q.fn.help.sh"
