#!/usr/bin/env bash

:go () {

    local target
    target=$(dirname $(my.which $1) 2>/dev/null) && {
        echo pushd to $target
        pushd $target > /dev/null
        return
    }
    echo not found: $1
    return 99
}

#case .$1 in .|.-h|.--help)cat<<EOF;;*)main $*;esac
#usage:
#    . $(basename ${BASH_SOURCE[0]}) <target>
#description:
#    wrap [which] to resolve symlinks.
#EOF


